addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp

Fixes a bug where jumpstats would not be registered until a certain tick was reached. This only happens when the map is changed and for every time this happens the amount of ticks until jumpstats work again is incremented.
How to replicate:
Once loaded in, change map. Jumpstats will not work for a little while. Repeat and the next time you're loaded in the amount of ticks until jumpstats work is incremented.

Set tickCount at initialization

---

PLUGINS.md
addons/sourcemod/scripting/gokz-profile/options.sp

This change will change the access check for the VIP and ADMIN tag to use command access instead of checking flags directly by using non-existent "commands". This will allow server administrators to override the admin flags required for accessing the tags by using Sourcemod's override system, thus not forcing specific flags to be used.

Overrides for tag access

---

addons/sourcemod/scripting/gokz-mode-kztimer.sp
addons/sourcemod/scripting/gokz-mode-simplekz.sp
addons/sourcemod/scripting/include/gokz.inc

Prestrafing now hooks GetPlayerMaxSpeed, which changes airacceleration, so I hooked AirAccelerate to cap it.
This could be done a bit easier by using m_flVelocityModifier since that doesn't modify maxspeed while in the air, **but** that causes another issue where if you jumpbug without perfing and have prestrafe your jump will have 250 pre or less because the game thinks that you're in the air. This fixes both issues.

Fix increased airaccel due to prestrafing

---

addons/sourcemod/scripting/gokz-core/map/triggers.sp

This should fix being able to checkpoint on bhop triggers.

Revert to using sdkhook for non mapping api triggers.

---

addons/sourcemod/scripting/gokz-jumpstats.sp
addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp
addons/sourcemod/scripting/gokz-jumpstats/jump_validating.sp

It is possible that InvalidateJumpstat is called, and then the jump gets validated in the same tick in DetermineType, causing a false jumpstat.

Invalidate jumps with externally modified velocity for one more tick

---

addons/sourcemod/scripting/gokz-core/map/triggers.sp

This is a simple fix for being able to jumpbug antibhop triggers.

Disable jumping while the in the air and in an antibhop trigger.

---

addons/sourcemod/scripting/include/gokz.inc

Clear the player's parent before teleporting in TeleportPlayer to fix being teleported into seemingly random places if the player has a parent.

Clear the player's parent before teleporting

---

addons/sourcemod/scripting/gokz-core/natives.sp
addons/sourcemod/scripting/gokz-core/timer/timer.sp
addons/sourcemod/scripting/gokz-global.sp
addons/sourcemod/scripting/include/gokz/core.inc

Every time someone uses saveloc, the run gets invalidated over and over again, leading to spam.

Prevent server console spam from run invalidation

---

addons/sourcemod/translations/gokz-tips-jumpstats.phrases.txt

Previously the !jumpstats command was a shortcut to the jumpstats
options. This has changed, and it now opens a menu that shows your
current JS records.

Update JS tips to reflect new commands

---

addons/sourcemod/scripting/gokz-core/triggerfix.sp

The plugin no longer adds trigger_push to the touch list if the player is already touching one previously.

Fix trigger_push boosting players more than once

---

addons/sourcemod/scripting/gokz-mode-simplekz.sp

TakeoffVelocity is defined in OnJumpPost, but we are nerfing the height during OnJumpPre. This should be easily resolved by getting the current velocity during movement processing instead.

Fix weirdjump real perf height being higher in SKZ

---

addons/sourcemod/scripting/gokz-profile.sp
addons/sourcemod/scripting/gokz-profile/options.sp

The goal of this pull request is to prevent the following edge cases:
1. Clientprefs might be shared between multiple servers and permissions differ among them, allowing you to set an "ADMIN" tag on  server 1 and have it be shown on server 2.
2. Prevent tags with permissions tied to them being visible if permissions are not met, this pull request defaults to showing the rank if their tag type is set to an option that they cannot access.
It should be noted that this does not override the saved option value when the client cannot access the tag type.
This behaviour allows for players to set "ADMIN" tag on a server they're an admin on, and persist that option even if they join another server that shares the clientprefs, but instead have their "RANK" tag being shown.

[gokz-profile] Fix stale tags being usable

---

addons/sourcemod/scripting/gokz-localranks/db/sql.sp

When ONLY_FULL_GROUP_BY is set on the SQL server, the queries before this
change failed with an error. The ONLY_FULL_GROUP_BY mode is set by
default on new MySQL installations at least, so we could assume that
this will happen more and more as time goes by.
This fix adds missing columns to the group bys that are in the inner
queries. It also removes the group by from the outer most one, as we
have already grouped the results earlier, and there should be no need to
do it again.
As a disclaimer though, I am not a SQL wizard, and there might be some
edge-cases where this could break..? Maybe?
Fixes #275.

Prevent SQL errors due to ONLY_FULL_GROUP_BY

---

addons/sourcemod/scripting/gokz-replays/playback.sp

Run replays display is unchanged
Jump replays now display as `KZT LJ BOT Szwagi (271.23)` or `KZT LJ BOT Szwagi (271.23 on 270 block)`
Jump replays bots only join the T team now, before it was based on leftover state of teleport count.

Improve replay bot name and clantags

---

addons/sourcemod/scripting/gokz-replays/playback.sp

Just bail out of loading and return an error if there is no tick data since that causes issues down the line.
[SM] Exception reported: Invalid index 0 (count: 0)
[SM] Blaming: gokz-replays.smx
[SM] Call stack trace:
[SM]   [0] ArrayList.GetArray
[SM]   [1] Line 834, gokz-replays/playback.sp::PlaybackVersion2
[SM]   [2] Line 295, gokz-replays/playback.sp::OnPlayerRunCmd_Playback
[SM]   [3] Line 209, gokz-replays.sp::OnPlayerRunCmd

Dont attempt to load replays with no tick data

---

addons/sourcemod/scripting/gokz-core/misc.sp
cfg/sourcemod/gokz/gokz.cfg

This was causing client-sided animation sequences to be messed up until a full-update happened.
I also changed the forced team to spectator to reduce AFK players blocking timers on maps with timers close to spawn points.

Fix forced team pick being run too early

---

addons/sourcemod/scripting/gokz-replays/playback.sp

If the first replay loaded by the bot is a version 1 replay, the block size will not be enough for version 2 replay.

Fix bot being stuck at 0,0,0 caused by invalid ArrayList block size

---

addons/sourcemod/scripting/gokz-global.sp
addons/sourcemod/translations/gokz-global.phrases.txt

In case the map is the wrong version, or the server is not updated the
user might not realize that the run will not be saved in the global api.
To avoid the confusion, we show them an error message.
To prevent spam of the message, we first check if the server is intended
to be global, by verifying that the GlobalApi plugin has a key set.
Further if the user already has a run going when resetting the timer,
they will not get the message again. If they stop the timer and start it
again, it will show the message again.
Implements: #316

Add warning message when starting a non-global run

---

addons/sourcemod/scripting/gokz-core/demofix.sp

The check is done before accessing the gamerules in the EnableDemoRecord
function when the demofix is enabled. When you have set Demofix to be
disabled it will attempt to access the Gamerules too early during map
load, causing an "Couldn't find gamerules proxy entity" exception.
This commit fixes that issue by making sure that we are only running the
SetProp when the map is actually running.
Fixes: #309

Check if map is running also when Demofix is disabled

---

addons/sourcemod/scripting/gokz-core/teleports.sp
addons/sourcemod/translations/gokz-core.phrases.txt

Adds a message that will show in case a player has the timer off and
creates a CP in an area that is marked to have CPs disabled. If the
timer is running, the player will not be able to create a CP.
It adds the message so that the user can test in what places its
possible to create CPs without having the timer on. This reduces
confusion and makes the routing process easier.
(Message edited after this, too lazy to take new screenshot...)
Implements #313

Show warning on CP in CP disabled area

---

addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp

Related to this PR here on MovementAPI: https://github.com/danzayau/MovementAPI/pull/27
I just add a check to prevent that from happening.

Ensure that ladderjump jumpstat isn't a ladderhop from midair

---

addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp

Fixes the bug where the angles of the first strafe of jumpbugs is not correct.

Update the first tick takeoff info in case of jumpbug

---

cfg/sourcemod/gokz/gokz.cfg

Server sided footsteps are more consistent, also replay bots make no sound climbing ladder without this change.

Use server sided footsteps

---

addons/sourcemod/scripting/gokz-core/misc.sp

Fix issue where players were still able to noclip out of a start zone because the jump is revalidated.
The following courses need to have its wr wiped (only the ones that I know of): kz_shark_gc B3, kz_delphinium B2

No longer validate jump if it was invalidated in the same tick

---

addons/sourcemod/scripting/gokz-jumpstats/jump_reporting.sp

This commit caused the jump report to no longer line up properly:  https://github.com/KZGlobalTeam/gokz/commit/812c99af6a17b303a3687f2e6b002c855958df56

Revert space to tab changes in jump reports

---

addons/sourcemod/scripting/gokz-core.sp
addons/sourcemod/scripting/gokz-core/map/triggers.sp

The intention of this is to fix being able to jumpbug the mapping api antibhop trigger if the trigger is <=11 units thick or if triggerhopping.

Fix antibhop trigger not working sometimes

---

addons/sourcemod/scripting/gokz-core/timer/timer.sp

This is a QOL feature. Mainly fixes the problem when players would accidentally press a bonus start button/trigger a bonus start zone while doing a run.
This could be a bit confusing for players who actually want to start a timer, though so a message would be nice, but I'm lazy.

When your timer is running, then don't restart the timer if you try to start a run on a different course

---

addons/sourcemod/scripting/gokz-replays/recording.sp
addons/sourcemod/scripting/include/gokz/replays.inc

Resolves #337.
The timer can reach up to 29 hours before failing, but it can fail as early as 14.5 hours, so I chose the 14 hours mark as the limit.

Stop the recording if its duration is too long

---

addons/sourcemod/scripting/gokz-replays.sp
addons/sourcemod/scripting/gokz-replays/playback.sp
addons/sourcemod/scripting/gokz-replays/recording.sp
addons/sourcemod/scripting/include/gokz/replays.inc
cfg/sourcemod/gokz/gokz.cfg

Resolves #335.
A fake client is not a bot. The client doesn't store data for interpolation if the bot isn't initialized properly. Using `bot_add` should preserve the "no bot in server" behavior. Modifying `bot_quota` cvar is also an option, but that might mess with other plugins that happen to use bots as well.
Bot name updating now no longer requires the player to be put out of spectator mode, `spec_target_updated` event is fired instead.

Use actual bots instead of fake client for interpolation, fix bots having no sound, increase bots limit, reworked name update logic

---

addons/sourcemod/scripting/gokz-saveloc.sp

Speculative fix for an issue where `FL_ONGROUND` flag is not correctly applied even though the player is on the ground, if the player manages to make a saveloc on the exact landing tick, breaking prestrafing and hud elements.

Track ground entity for saveloc

---

addons/sourcemod/scripting/gokz-global.sp
addons/sourcemod/scripting/gokz-global/send_run.sp
addons/sourcemod/scripting/gokz-replays/api.sp
addons/sourcemod/scripting/gokz-replays/recording.sp
addons/sourcemod/scripting/include/gokz/replays.inc

Resolves #323.
Right now a run will only gets uploaded if it beats the server record. Now it will be uploaded if it beats the player's PB instead.
It is possible to get the world record without beating the server record (eg. map exists before it gets global). This should also be useful for cheated run checks, as not every cheated run would beat SR.
I haven't (couldn't) tested this out as it is not possible for me to do so without staging API access.

Always upload replays on personal best

---

addons/sourcemod/scripting/gokz-hud.sp

Fix gokz-hud spewing errors at the end of replay playback, as the replay bot is kicked off the server.

Fix hud errors related to replay playback

---

addons/sourcemod/scripting/gokz-replays/playback.sp
addons/sourcemod/scripting/gokz-replays/replay_menu.sp

`botReplayType[bot]` and `botTeleportsUsed[bot]` is not loaded in yet by the time the bot gets added.
`info.OnLadder` is now correct, and is necessary for dead strafe indicator to work properly. The indicator still doesn't work well with old replays because they didn't track movetypes.

Fix replay bots joining the incorrect teams, fix OnLadder HudInfo not being correct

---

addons/sourcemod/scripting/gokz-core.sp
addons/sourcemod/scripting/gokz-core/map/triggers.sp

Use client tick count for trigger touch time calculation

---

addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp

Resolves #363. Also mentioned in #364, we should avoid using server tick if possible for any movement tracking.

Use client tick for jump tracking tick and invalidate duckbugged longjumps

---

addons/sourcemod/scripting/gokz-jumpstats.sp
addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp

Apparently it is possible to stop touching an entity before you can even touch it, allowing players to register wallstrafe LJ as long jump stats. (in kz_lovesick magic wheel for instance).
By tracking the full list of entities, bogus like this shouldn't happen anymore.

Track touching entities for jumpstats

---

addons/sourcemod/scripting/gokz-hud/info_panel.sp

This prevents division by 0 error. (Thanks @Szwagi !)

Limit the maximum update speed to prevent crashes on LAN

---

addons/sourcemod/scripting/gokz-localdb/db/save_js.sp

Small oversight for the localdb module, a jump should be saved as you can land closer than 0.03125u to the ground.
Happens when you jump > cperf > perf > perf on kzt.

Save valid jumps that have very small offset

---

addons/sourcemod/scripting/gokz-core/timer/pause.sp
addons/sourcemod/scripting/gokz-core/timer/timer.sp
addons/sourcemod/scripting/gokz-hud/menu.sp

The client menu works half of the time when the players use start timer button zone,

Fix unresponsive client menu when players use start timer button zone, fix errors showing up if players try to pause in start timer button zone

---

addons/sourcemod/scripting/gokz-global/send_run.sp

This might fix the error that prevents replays from being sent to the API. This got through my testing because, well, I don't have access to the staging API.

Initialize replay datapack

---

addons/sourcemod/scripting/gokz-core.sp

This function only works on for triggers/buttons, hooking player entities just causes lag spikes and nothing else.

Reduce lag spikes upon player spawn

---

addons/sourcemod/scripting/gokz-global.sp
addons/sourcemod/scripting/include/SteamWorks.inc

Apparently that wasn't the case before...

Only enable global plugin on VAC secured servers

---

addons/sourcemod/scripting/gokz-saveloc.sp

Current duration is way too long and makes some start timer techs no longer feasible or very awkward (eg. kz_scicret bonus on VNL where accelerating from 0 to 85 takes a lot of time, or kz_mz), this new duration should be closer to the duration used in `sm_start`.

Reduce loadloc invalidation duration

---

addons/sourcemod/scripting/gokz-anticheat.sp
addons/sourcemod/scripting/gokz-chat.sp
addons/sourcemod/scripting/gokz-core.sp
addons/sourcemod/scripting/gokz-errorboxfixer.sp
addons/sourcemod/scripting/gokz-global.sp
addons/sourcemod/scripting/gokz-goto.sp
addons/sourcemod/scripting/gokz-hud.sp
addons/sourcemod/scripting/gokz-jumpbeam.sp
addons/sourcemod/scripting/gokz-jumpstats.sp
addons/sourcemod/scripting/gokz-localdb.sp
addons/sourcemod/scripting/gokz-localranks.sp
addons/sourcemod/scripting/gokz-measure.sp
addons/sourcemod/scripting/gokz-mode-kztimer.sp
addons/sourcemod/scripting/gokz-mode-simplekz.sp
addons/sourcemod/scripting/gokz-mode-vanilla.sp
addons/sourcemod/scripting/gokz-momsurffix.sp
addons/sourcemod/scripting/gokz-paint.sp
addons/sourcemod/scripting/gokz-pistol.sp
addons/sourcemod/scripting/gokz-playermodels.sp
addons/sourcemod/scripting/gokz-profile.sp
addons/sourcemod/scripting/gokz-quiet.sp
addons/sourcemod/scripting/gokz-racing.sp
addons/sourcemod/scripting/gokz-replays.sp
addons/sourcemod/scripting/gokz-saveloc.sp
addons/sourcemod/scripting/gokz-slayonend.sp
addons/sourcemod/scripting/gokz-spec.sp
addons/sourcemod/scripting/gokz-tips.sp
addons/sourcemod/scripting/include/gokz.inc

Corrects plugin source urls to point to this GitHub repository instead of the old Bitbucket repository.
This creates a new `GOKZ_SOURCE_URL` constant in `gokz.inc` that should be used for future modules/plugins.

Fix plugin source urls

---

addons/sourcemod/scripting/gokz-core/commands.sp
addons/sourcemod/scripting/gokz-core/misc.sp

!safe being ternary seems to make a lot of people confused, so it only toggles between nub and disabled. `!pro` still works as usual.

Disable killbind for safeguard, make !safe binary instead of ternary

---

addons/sourcemod/scripting/gokz-core.sp
addons/sourcemod/scripting/gokz-profile.sp

Clan tag change block should belong in the plugin that modify clan tags. Some server owners want to enable player clan tags and disable the profile plugin.

Move clantag block to gokz-profile

---

addons/sourcemod/scripting/gokz-quiet.sp

Previously when someone spawns, you can still hear the armor equip and ammo pickup sounds, the knife hitting the ground sound, and the blood sound if the someone shoots you, even with `!hide` on.
This fixes that and adds late loading support as well.

Add late loading support for gokz-quiet, block extra sounds with !hide

---

addons/sourcemod/scripting/gokz-spec.sp

Previously if you are spectating someone, but your timer is on, and the spectated player is in mid-air, you cannot spectate other players.

Allow player to spectate other players with timer on while in spectate

---

addons/sourcemod/scripting/gokz-quiet.sp

During the weapon sound hook the list of clients can contain invalid clients somehow.
Also fix the sound hook using the wrong functions to set variables.

Fix potential sound hook crash and add valid client check to weapon sound to prevent errors

---

addons/sourcemod/scripting/gokz-global.sp

This fixes an issues that might happen in the following scenario:
1. Unbanned player joins.
2. Unbanned player leaves.
3. Global API goes offline.
4. A Banned player joins, and gets the same client id as the unbanned player had. This causes him to be seen as Unbanned.
5. The Banned player plays, etc.
6. API goes up, and requests are now being sent to the Global API as a part of the retry proccess, causing multiple bans etc. to appear.
To prevent this, we reset the status of a client to not be Globally verified when joining the server, so that we always start from a clean state when the Global Ban check is done in OnClientPostAdminCheck.

Reset globally verified status on player join

---

addons/sourcemod/scripting/gokz-core/triggerfix.sp

Fix targetname spam allowing player to get double boosted by triggerfix (kz_fly_lovers). Fortunately, WR is not boosted because getting double boosted is slower.

Really ignore trigger_push for triggerfix

---

addons/sourcemod/scripting/gokz-global.sp

`SteamWorks_IsVACEnabled` can be called before SteamWorks is actually ready, leading into VAC check failing. Also this might not work if you launch the server while steam is down, which is... not good.
This one checks for the launch options that disables VAC instead.

Hotfix for VAC check

---

addons/sourcemod/scripting/gokz-core/timer/timer.sp
addons/sourcemod/scripting/gokz-core/timer/virtual_buttons.sp

If you `!ssp` and setup timer tech for a button course, then start a course using zones, then do `!start`, the timer for the zone course does not get stopped. Caused by #346.

Fix going to custom start not stopping timer

---

addons/sourcemod/scripting/gokz-localranks/db/sql.sp
addons/sourcemod/scripting/gokz-localranks/db/update_ranked_map_pool.sp
addons/sourcemod/translations/gokz-localranks.phrases.txt
cfg/sourcemod/gokz/gokz-localranks-mappool.cfg

Refactors `sm_updatemappool` to use transactions for the map queries.
This will fix #391, which has been popping up often lately, as the map list has grown to the point where SM runs out of heap.
This has been tested locally on SQLite (SM 1.11.0.6911) and MySQL 5.7.35.
This PR also raises the buffer size of a line being read to get around `fgets` weirdness, which `File.ReadLine` uses.
If the line exceeds the old 32 character limit, the very next `File.ReadLine` will now contain the rest of the previous line.
> The C library function char *fgets(char *str, int n, FILE *stream) reads a line from the specified stream and stores it into the string pointed to by str. **It stops when either (n-1) characters are read**, the newline character is read, or the end-of-file is reached, whichever …

Refactor sm_updatemappool to use transactions

---

addons/sourcemod/scripting/gokz-hud/racing_text.sp
addons/sourcemod/scripting/gokz-hud/speed_text.sp
addons/sourcemod/scripting/gokz-hud/timer_text.sp
addons/sourcemod/scripting/include/gokz.inc

Related to #419, but does not really fix it because MHUD is still at fault.
The reuse logic with 6 channels is fine, and is not why the HUD text was unable to be displayed.
The cause is the client's internal message buffer which is 16 slots long and shared between 6 channels at once. The message in the buffer will only clear once the hold time is over. So a plugin sending one HUD message lasting for 0.5 seconds will immediately fill the buffer (that's 64 messages, which is way past 16), leaving no place for other plugins. 
The reason joining team or sending `round_start` event temporarily fixes the issue is because they trigger the message buffer wipe, but they come with other unwanted side effects. 
[Reference](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d …

Fix HUD text display taking over other plugins' display

---

addons/sourcemod/gamedata/gokz-core.games.txt

NOT related to the latest CSGO update, but still seems to be a mismatch from the "upstream"?
Latest values from https://github.com/jason-e/rngfix.

Update rngfix gamedata

---

addons/sourcemod/scripting/gokz-core.sp
addons/sourcemod/scripting/gokz-core/triggerfix.sp
addons/sourcemod/scripting/include/gokz/core.inc

Hotfix for side effect caused by #455.
Before the triggerfix code just doesn't work at all, probably. Fixes kz_noobfort and similar map with a filter setting trigger using `OnTrigger` freezing on the first jump.
This might actually finally patch some trigger cancelling shenanigans that were still around, to be tested. (Doesn't seem like it though)

Fix triggerfix infinitely looping on triggers using OnTrigger

---

addons/sourcemod/scripting/gokz-hud/info_panel.sp

This is pretty huge. Previously the hint text panel update speed depends on the client ping, this is because the message is sent in a reliable channel. This means it will update really slowly if the client latency is significant. Besides, for something that updates as often as the info panel, that is not necessary. This change will finally make the info panel usable on high ping situations.

Make info panel text non reliable to increase update speed on high ping scenarios

---

addons/sourcemod/scripting/gokz-hud/info_panel.sp

Apparently a blank message leads to the client freezing. This PR fixes it.

Fix client freezing with empty center hud text

---

addons/sourcemod/gamedata/gokz-tpanglefix.games.txt
addons/sourcemod/scripting/gokz-tpanglefix.sp

Fix gamedata (hopefully) and make sure the parallel snapshot cvar is off.
Fix to #472.

Fix tpanglefix crashing servers on linux

---

addons/sourcemod/scripting/gokz-core/misc.sp

Fixes an exploit that let players use a timer through players from very far away.
Did what GameChaos said should be done.
Recreated the exploit and then tested this fix.

Fix timer +use through player exploit

---

addons/sourcemod/scripting/gokz-global.sp

Fix steam_id_stop_ignoring_retvals profile queries to the api.

Add missing client auth check for points update

---

addons/sourcemod/scripting/gokz-jumpstats.sp
addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp

Fix a rare bug where your jump gets invalidated if the client/server gets a performance spike and spews broken jsalways stats like this:
```
zer0.k jumped 231.2947 units with a Multi Bunnyhop
KZT | 6 Strafes | 71% Sync | 243.86 Pre | 294.15 Max | 2 OL | 16 DA | 21.1° Width | 55.8 Height | 96 Airtime | 0.0 Offset | 0 Crouched
#.  Sync      Gain      Loss      Airtime   Width     OL     DA     
1.   88%       6.97      0.00       9%       12.0°     0      1
2.   70%      10.78      0.74      20%       26.8°     2      2
3.   75%      281.33     270.51      20%       25.4°     0      3
4.   80%      12.18      0.00      20%       28.6°     0      2
5.   73%      10.27      0.00      19%       25.7°     0      3
6.   25%       1.54      2.46       8%        8.4°     0      5
```

Only track jump during movement processing
