addons/sourcemod/scripting/include/gokz.inc

It checked the wrong origin that was 0 0 0.

Fix valid spawn logic

---

addons/sourcemod/scripting/gokz-core/misc.sp

I messed up the logic, should be the other way around.

Fix player collision logic being the other way around

---

addons/sourcemod/scripting/gokz-replays/playback.sp
addons/sourcemod/scripting/gokz-replays/recording.sp

Not sure if we'll end up doing this, but might simplify recording buffer management a lot.

Various replay buffer changes

---

addons/sourcemod/scripting/gokz-measure.sp
addons/sourcemod/scripting/gokz-measure/commands.sp
addons/sourcemod/scripting/gokz-measure/measurer.sp

Resolves Szwagi's request from #225

Add valid client check for measure commands, measure the block when the distance is under 0.01 unit

---

addons/sourcemod/scripting/gokz-core/timer/pause.sp

Sets the client's collision group upon unpausing.

Fix unpause noclip exploit

---

addons/sourcemod/scripting/gokz-profile.sp
addons/sourcemod/scripting/gokz-profile/profile.sp

- Fix situations where clients are iterated to not miss the last client index.

[gokz-profile] Fix client iteration

---

addons/sourcemod/scripting/gokz-global.sp

Pass client as userid to the kick callback

FPS check: pass client as userid to the kick callback

---

addons/sourcemod/scripting/gokz-core/commands.sp
addons/sourcemod/scripting/gokz-core/map/triggers.sp
addons/sourcemod/scripting/gokz-core/misc.sp

Fixes teleport/antibhop triggers triggering multiple times and staying on forever.
Blocks team change to spectator in jointeam hook if the player's timer is running and they can't pause.

Fix mapping api bugs

---

addons/sourcemod/scripting/gokz-replays.sp
addons/sourcemod/scripting/gokz-replays/playback.sp

Dynamically add bots to server when needed instead of leaving them sitting in spectator mode

---

addons/sourcemod/scripting/gokz-hud/options.sp
addons/sourcemod/scripting/gokz-hud/options_menu.sp
addons/sourcemod/scripting/gokz-hud/tp_menu.sp
addons/sourcemod/scripting/include/gokz/hud.inc
addons/sourcemod/scripting/include/gokz/kzplayer.inc
addons/sourcemod/translations/gokz-hud.phrases.txt

Resolves #154 
Ripped code from KZTimer and adapted it here.

Add option to show who's spectating you

---

addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp
addons/sourcemod/scripting/include/gokz.inc

Ladderglide detection logic is rewritten so ladderhop works again.

Fix broken ladderhop detection

---

addons/sourcemod/scripting/gokz-core/triggerfix.sp

Temporary fix for booster giving you way more speed than intended (eg. kz_fly_lovers).

Ignore triggerfix for trigger_push

---

addons/sourcemod/scripting/gokz-replays/playback.sp

Fix replay bots having no valid ground entity while on the ground

---

addons/sourcemod/scripting/gokz-replays/recording.sp

Create RP_DIRECTORY_RUNS_TEMP directory

---

addons/sourcemod/scripting/gokz-saveloc.sp

Track last position at full crouch speed for saveloc

---

addons/sourcemod/scripting/gokz-saveloc.sp

Don't let the player start the timer right after loadloc.

Prevent saveloc abuse with boosters

---

addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp

actualSpeed being tickrate hardcoded breaks jumpstats on non 128 tick.
You could edgebug on vanilla to save your stamina and get massive wj distance, in theory that should also work on KZT as well. So now that's fixed.
Previously failstats registers the block distance for the real stats as well, that allowed 250 distance jumps to have 320 block distance. That's also fixed by making sure the block distance value is set correctly.

Fix jumptracking actualSpeed being tickrate hardcoded, invalidate edgebugged stats, fix failstats block distance getting applied to current jump

---

cfg/sourcemod/gokz/gokz.cfg

The grey fading effect thing was pretty annoying.

Disable fading effect with demofix enabled

---

addons/sourcemod/scripting/gokz-jumpstats.sp
addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp

Fix jumpstats abuse with AddOutput origin

---

addons/sourcemod/scripting/include/gokz.inc

Fix !end in kz_sc_surf being broken.

Take parent entities into account in GetEntityPositions

---

addons/sourcemod/scripting/gokz-replays.sp
addons/sourcemod/scripting/gokz-replays/playback.sp

Fix bot using the wrong timer sound

---

addons/sourcemod/gamedata/gokz-replays.games.txt
addons/sourcemod/scripting/gokz-replays.sp
addons/sourcemod/scripting/gokz-replays/playback.sp
addons/sourcemod/scripting/gokz-replays/replay_menu.sp

Originally part of #358, now split up into smaller PRs.
This one resolves #403 and fix the bug where the bot does not join if the server is running low on free slots.

Rework bot joining method

---

addons/sourcemod/gamedata/gokz-replays.games.txt
addons/sourcemod/scripting/gokz-core/misc.sp
addons/sourcemod/scripting/gokz-core/natives.sp
addons/sourcemod/scripting/gokz-replays.sp
addons/sourcemod/scripting/gokz-replays/playback.sp
addons/sourcemod/scripting/gokz-replays/replay_menu.sp
addons/sourcemod/scripting/include/gokz/core.inc

Separated off #358, requires #413 to be approved first.

Fix bots not being hidden by !hide

---

addons/sourcemod/translations/gokz-common.phrases.txt
addons/sourcemod/translations/gokz-core.phrases.txt
addons/sourcemod/translations/gokz-global.phrases.txt
addons/sourcemod/translations/gokz-hud.phrases.txt
addons/sourcemod/translations/gokz-jumpstats.phrases.txt
addons/sourcemod/translations/gokz-localdb.phrases.txt
addons/sourcemod/translations/gokz-localranks.phrases.txt
addons/sourcemod/translations/gokz-measure.phrases.txt
addons/sourcemod/translations/gokz-paint.phrases.txt
addons/sourcemod/translations/gokz-profile.phrases.txt
addons/sourcemod/translations/gokz-quiet.phrases.txt
addons/sourcemod/translations/gokz-racing.phrases.txt
addons/sourcemod/translations/gokz-replays.phrases.txt
addons/sourcemod/translations/gokz-saveloc.phrases.txt
addons/sourcemod/translations/gokz-tips-core.phrases.txt
addons/sourcemod/translations/gokz-tips-hud.phrases.txt
addons/sourcemod/translations/gokz-tips-jumpstats.phrases.txt
addons/sourcemod/translations/gokz-tips-localranks.phrases.txt
addons/sourcemod/translations/gokz-tips-quiet.phrases.txt
addons/sourcemod/translations/gokz-tips-tips.phrases.txt
addons/sourcemod/translations/gokz-tips.phrases.txt

add simplified chinese translation

---

addons/sourcemod/scripting/gokz-quiet.sp

Fix exceptions from putting empty array into datapack

---

addons/sourcemod/scripting/include/gokz.inc

Add valid client check to GetObserverTarget

---

addons/sourcemod/translations/gokz-paint.phrases.txt
addons/sourcemod/translations/gokz-racing.phrases.txt

Additional fixes for English translations that were cause by copy-paste errors in https://github.com/KZGlobalTeam/gokz/pull/431

Fix translations

---

addons/sourcemod/scripting/gokz-core/map/zones.sp
addons/sourcemod/scripting/gokz-core/natives.sp
addons/sourcemod/scripting/gokz-core/timer/timer.sp
addons/sourcemod/scripting/gokz-core/timer/virtual_buttons.sp
addons/sourcemod/scripting/include/gokz/core.inc

Starting zone timer will delete virtual buttons made by buttons.

Fix going to custom start not stopping timer (for real this time)

---

addons/sourcemod/gamedata/gokz-momsurffix.games.txt

Latest version from https://github.com/GAMMACASE/MomSurfFix.
To fix issues with CSGO  February 2nd update.

Update momsurffix gamedata from upstream

---

addons/sourcemod/scripting/gokz-jumpstats.sp
addons/sourcemod/scripting/gokz-jumpstats/jump_tracking.sp
addons/sourcemod/scripting/include/movementapi.inc

If you leave the ladder from the ground with W+A/D and then jump at the exact tick you stop being on the ladder, you get a long jump with extremely high pre.
Also remove some unused code.

Fix ladder takeoff on the ground counting as long jump

---

addons/sourcemod/scripting/gokz-replays/playback.sp

Fix TP bot having broken interpolation after teleporting and bot having bogus movetype after tick skipping

---

addons/sourcemod/scripting/gokz-momsurffix.sp
addons/sourcemod/scripting/momsurffix/gametrace.sp

Mostly some things that have been badly copied over, or have been changed later on.
Original find by Yue-Ra, which made me recheck bigger parts of the momsurffix code.

Update momsurffix with upstream changes

---

addons/sourcemod/scripting/include/gokz.inc

We should use ducked and not ducking to set the player state to fully ducked.

Fix paused tp abuse with ladders

---

addons/sourcemod/scripting/gokz-quiet/hideplayers.sp

... and breaking gokz's hud and chat processor and every hud element....

Fix gokz-quiet disabling all user messages

---

addons/sourcemod/scripting/gokz-tpanglefix.sp

Fix performance of this plugin being really bad.

No longer update memory access for tp angle byte patching

---

addons/sourcemod/scripting/gokz-replays/controls.sp
addons/sourcemod/scripting/gokz-replays/playback.sp

[This bug](https://www.youtube.com/watch?v=e3rlvBRgrFg&t=294s) has been bothering me for a while but only now I found the fix for it.

Fix replay menu control compilation warning, fix player head getting inside the ceiling while ducked

---

.github/workflows/main.yml
addons/sourcemod/scripting/gokz-mode-kztimer.sp
addons/sourcemod/scripting/gokz-mode-simplekz.sp
addons/sourcemod/scripting/gokz-mode-vanilla.sp
addons/sourcemod/scripting/gokz-saveloc.sp

GOKZ v3.6.3

---

.github/workflows/main.yml

The old one is no longer supported.

Update CI ubuntu version
